<a href="https://colab.research.google.com/github/ciepielajan/SDA_SMOG_Wawelski/blob/main/Jan/SDA_2021_04_11_Projekt_koncowy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 Załadowanie plików







In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob

In [2]:
!gdown --id "186S03hFJ67K4eV1BWb2_6lZxAYG7dBM4"

Downloading...
From: https://drive.google.com/uc?id=186S03hFJ67K4eV1BWb2_6lZxAYG7dBM4
To: /content/archive.zip
2.39MB [00:00, 74.9MB/s]


In [3]:
!unzip -q "archive.zip" -d data/

In [4]:
all_file_names = glob.glob("data/*2017.csv")
all_file_names = sorted(all_file_names)
for counter, file in enumerate(all_file_names):
    print(counter, file)

0 data/april-2017.csv
1 data/august-2017.csv
2 data/december-2017.csv
3 data/february-2017.csv
4 data/january-2017.csv
5 data/july-2017.csv
6 data/june-2017.csv
7 data/march-2017.csv
8 data/may-2017.csv
9 data/november-2017.csv
10 data/october-2017.csv
11 data/september-2017.csv


In [5]:
jan = pd.read_csv(all_file_names[4])
feb = pd.read_csv(all_file_names[3])
mar = pd.read_csv(all_file_names[7])
apr = pd.read_csv(all_file_names[0])
may = pd.read_csv(all_file_names[8])
jun = pd.read_csv(all_file_names[6])
jul = pd.read_csv(all_file_names[5])
aug = pd.read_csv(all_file_names[1])
sep = pd.read_csv(all_file_names[11])
octo = pd.read_csv(all_file_names[10])
nov = pd.read_csv(all_file_names[9])
dec = pd.read_csv(all_file_names[2])

In [6]:
dec.head(1)

UTC time  3_temperature  3_humidity  ...  895_pm1  895_pm25  895_pm10
0  2017-12-01T00:00:00            NaN         NaN  ...       34        36        66

[1 rows x 337 columns]

In [7]:
sensors = pd.read_csv("data/sensor_locations.csv")

In [8]:
sensors[:3]

id   latitude  longitude
0    3  50.057748  19.961375
1  140  50.057747  19.961374
2  142  50.084816  19.878066

2 Połączenie wszystkich df


In [9]:
year = pd.concat([jan, feb, mar, apr, may, jun, jul, aug, sep, octo, nov, dec])

In [10]:
year.shape

(8593, 337)

In [11]:
year.head(2)

UTC time  3_temperature  3_humidity  ...  895_pm1  895_pm25  895_pm10
0  2017-01-01T00:00:00            NaN         NaN  ...      NaN       NaN       NaN
1  2017-01-01T01:00:00            NaN         NaN  ...      NaN       NaN       NaN

[2 rows x 337 columns]

3 Transformacja df







In [12]:
year["UTC time"] = pd.to_datetime(year["UTC time"], format="%Y-%m-%dT%H:%M:%S")
year[:3]

UTC time  3_temperature  3_humidity  ...  895_pm1  895_pm25  895_pm10
0 2017-01-01 00:00:00            NaN         NaN  ...      NaN       NaN       NaN
1 2017-01-01 01:00:00            NaN         NaN  ...      NaN       NaN       NaN
2 2017-01-01 02:00:00            NaN         NaN  ...      NaN       NaN       NaN

[3 rows x 337 columns]

In [13]:
year = year.set_index("UTC time")
year[:3]

3_temperature  3_humidity  ...  895_pm25  895_pm10
UTC time                                        ...                    
2017-01-01 00:00:00            NaN         NaN  ...       NaN       NaN
2017-01-01 01:00:00            NaN         NaN  ...       NaN       NaN
2017-01-01 02:00:00            NaN         NaN  ...       NaN       NaN

[3 rows x 336 columns]

In [14]:
year.index[:3]

DatetimeIndex(['2017-01-01 00:00:00', '2017-01-01 01:00:00',
               '2017-01-01 02:00:00'],
              dtype='datetime64[ns]', name='UTC time', freq=None)

In [15]:
new_df = pd.DataFrame()

In [16]:
for i in year.groupby(year.columns.str.split('_').str[0], axis=1):
  old = i[1].columns
  new = i[1].columns.str.split("_").str[1]
  zmiana = { k:v  for k,v in zip(old,new)}
  i[1].rename(columns=zmiana,inplace=True)
  i[1]["id"] = i[0]
  new_df = new_df.append(i[1])
  # print(i[1])

In [17]:
new_df[:3]

temperature  humidity  pressure  pm1  pm25  pm10   id
UTC time                                                                  
2017-01-01 00:00:00          NaN       NaN       NaN  NaN   NaN   NaN  140
2017-01-01 01:00:00          NaN       NaN       NaN  NaN   NaN   NaN  140
2017-01-01 02:00:00          NaN       NaN       NaN  NaN   NaN   NaN  140

3.2 Połaczenie wartości z konkretnymi lokalizacjami wg ID sensoru

In [18]:
new_df["id"] = new_df["id"].astype(int)
sensors["id"] = sensors["id"].astype(int)

In [19]:
new_df = new_df.reset_index()

In [20]:
geo_df = new_df.merge(sensors, how='left', on='id')
geo_df[:3]

UTC time  temperature  humidity  ...   id   latitude  longitude
0 2017-01-01 00:00:00          NaN       NaN  ...  140  50.057747  19.961374
1 2017-01-01 01:00:00          NaN       NaN  ...  140  50.057747  19.961374
2 2017-01-01 02:00:00          NaN       NaN  ...  140  50.057747  19.961374

[3 rows x 10 columns]

4 EDA

In [21]:
geo_df.shape

(481208, 10)

4.1. Ile jest Nan w danych kolumnach

In [22]:
geo_df.isnull().sum()

UTC time            0
temperature    109558
humidity       109638
pressure       172529
pm1             92854
pm25            92835
pm10            92832
id                  0
latitude            0
longitude           0
dtype: int64

4.2. Czy można znaleźć brakujące dane lub czymś je zastąpić

In [23]:
geo_df = geo_df.dropna()
geo_df.shape

(291754, 10)

5 Zmiana danych na kategoryczne - Rozbicie TimeSeries na dzień, miesiąc etc


In [24]:
import warnings
warnings.filterwarnings("ignore")

In [25]:
geo_df["M"] = geo_df["UTC time"].dt.month
geo_df["D"] = geo_df["UTC time"].dt.day
geo_df["H"] = geo_df["UTC time"].dt.hour
# geo_df["Week"] = geo_df["UTC time"].dt.week
# geo_df["day of  Week"] = geo_df["UTC time"].dt.dayofweek
# geo_df["Weekend"] = geo_df["UTC time"].dt.dayofweek.apply(lambda x: "1" if x in [5,6] else "0"   )
# geo_df["day of  Year"] = geo_df["UTC time"].dt.dayofyear
# geo_df["Quorter"] = geo_df["UTC time"].dt.quarter
geo_df

UTC time  temperature  humidity  ...   M   D   H
1811   2017-03-17 11:00:00         12.0      44.0  ...   3  17  11
1812   2017-03-17 12:00:00         12.0      45.0  ...   3  17  12
1813   2017-03-17 13:00:00         12.0      43.0  ...   3  17  13
1814   2017-03-17 14:00:00         12.0      45.0  ...   3  17  14
1815   2017-03-17 15:00:00         12.0      50.0  ...   3  17  15
...                    ...          ...       ...  ...  ..  ..  ..
481203 2017-12-24 20:00:00          5.0      85.0  ...  12  24  20
481204 2017-12-24 21:00:00          5.0      85.0  ...  12  24  21
481205 2017-12-24 22:00:00          5.0      82.0  ...  12  24  22
481206 2017-12-24 23:00:00          5.0      85.0  ...  12  24  23
481207 2017-12-25 00:00:00          5.0      85.0  ...  12  25   0

[291754 rows x 13 columns]

6 Normalizacja współrzędnych - Standard scaller lub wzór (-50x1000)

7 Predykcja - szukanie najlepszego modelu

7.1 Regression

In [26]:
X = geo_df[["temperature",	"humidity","pressure","latitude","longitude","M","D",	"H"]]
X[:3]

temperature  humidity  pressure   latitude  longitude  M   D   H
1811         12.0      44.0  101244.0  50.057747  19.961374  3  17  11
1812         12.0      45.0  101147.0  50.057747  19.961374  3  17  12
1813         12.0      43.0  101049.0  50.057747  19.961374  3  17  13

In [27]:
y = geo_df["pm10"]
y[:3]

1811    22.0
1812    26.0
1813    26.0
Name: pm10, dtype: float64

7.1.1 Regresja liniowa

In [28]:
from sklearn.linear_model import LinearRegression

7.1.1.2 Regresja liniowa Podstawowy model

In [36]:
model = LinearRegression()
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
#wygenerowanie danych do testowej predykcji
val_1812 = geo_df[["temperature",	"humidity","pressure","latitude","longitude","M","D",	"H"]].iloc[1812].values
df_predict = pd.DataFrame([val_1812], columns=["temperature",	"humidity","pressure","latitude","longitude","M","D",	"H"])
df_predict

temperature  humidity  pressure   latitude  longitude    M    D     H
0         24.0      37.0  101792.0  50.057747  19.961374  6.0  3.0  11.0

In [37]:
#przewidziało
prediction = model.predict(df_predict)
prediction

array([1.6007795])

In [34]:
#powinno być
geo_df["pm10"].iloc[1812]

6.0

7.1.1.3 Regresja liniowa - Dostrajanie modelu np grid search

7.1.2.1 RandomForestRegressor()

In [35]:
from sklearn.ensemble import RandomForestRegressor

7.1.2.2 RandomForestRegressor() - Podstawowy model

In [38]:
model = RandomForestRegressor()
model.fit(X, y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [39]:
#wygenerowanie danych do testowej predykcji
val_1812 = geo_df[["temperature",	"humidity","pressure","latitude","longitude","M","D",	"H"]].iloc[1812].values
df_predict = pd.DataFrame([val_1812], columns=["temperature",	"humidity","pressure","latitude","longitude","M","D",	"H"])
df_predict

temperature  humidity  pressure   latitude  longitude    M    D     H
0         24.0      37.0  101792.0  50.057747  19.961374  6.0  3.0  11.0

In [40]:
#przewidziało
prediction = model.predict(df_predict)
prediction

array([6.45])

In [41]:
#powinno być
geo_df["pm10"].iloc[1812]

6.0

7.1.2.3 RandomForestRegressor() - Dostrajanie modelu np grid search

7.2 Predykcja TimeSeries

7.2.1 arima (pmd arima auto-arima)

7.2.2 Profet

7.3 RNN

7.3.1 LSTM

7.3.1.1 LSTM - Podstawowy

7.3.1.2 LSTM - Dwukierunkowy

7.3.2 GRU

7.3.2.1 GRU - Podstawowy

7.3.2.2 GRU - Dwukierunkowy

8 Zestawienie wyników predykcji - wybranie najlepszego modelu do predykcji 

9 Obliczenie predykcji dla nowej daty dla wszystkich punktów pomiarowych np 2018.01.21

10 Prototyp

10.1 Utworzenie siatki punktów w na terenie całego krakowa zlokalizowanych co 500m

In [42]:
left_top_corner =  [50.107 ,19.82]

points = pd.DataFrame()

for i in range(45):
  id_i = str(i+1) 
  i = i * 0.00463  # im mniejsza wartość tym bliższe odległości od kolejnego punktu
  for x in range(35):
    id = id_i + "-" + str(x+1)
    x = x * 0.00297      # im mniejsza wartość tym bliższe odległości od kolejnego punktu
    lat = left_top_corner[0] - x
    lon = left_top_corner[1] + i
    pm10= 0
    points = points.append({"id":id,"Latitude":lat,"Longitude":lon,"PM10":pm10},ignore_index=True)

points

Latitude  Longitude  PM10     id
0     50.10700   19.82000   0.0    1-1
1     50.10403   19.82000   0.0    1-2
2     50.10106   19.82000   0.0    1-3
3     50.09809   19.82000   0.0    1-4
4     50.09512   19.82000   0.0    1-5
...        ...        ...   ...    ...
1570  50.01790   20.02372   0.0  45-31
1571  50.01493   20.02372   0.0  45-32
1572  50.01196   20.02372   0.0  45-33
1573  50.00899   20.02372   0.0  45-34
1574  50.00602   20.02372   0.0  45-35

[1575 rows x 4 columns]

10.2 Obliczenie predykcji dla wszystkich stacji pomiarowych dla 2018.01.21

In [44]:
#wygenerowanie danych do testowej predykcji
val_1812 = geo_df[["temperature",	"humidity","pressure","M","D",	"H"]].iloc[1812].values
df_predict = pd.DataFrame([val_1812], columns=["temperature",	"humidity","pressure","M","D",	"H"])
df_predict

temperature  humidity  pressure    M    D     H
0         24.0      37.0  101792.0  6.0  3.0  11.0

In [52]:
points["temperature"] = df_predict["temperature"].iloc[0]
points["humidity"] = df_predict["humidity"].iloc[0]
points["pressure"] = df_predict["pressure"].iloc[0]
points["M"] = df_predict["M"].iloc[0]
points["D"] = df_predict["D"].iloc[0]
points["H"] = df_predict["H"].iloc[0]
points[:3]

Latitude  Longitude  PM10   id  ...  pressure    M    D     H
0  50.10700      19.82   0.0  1-1  ...  101792.0  6.0  3.0  11.0
1  50.10403      19.82   0.0  1-2  ...  101792.0  6.0  3.0  11.0
2  50.10106      19.82   0.0  1-3  ...  101792.0  6.0  3.0  11.0

[3 rows x 10 columns]

In [53]:
points = points[["temperature",	"humidity","pressure","Latitude","Longitude","M","D",	"H"]]
points[:3]

temperature  humidity  pressure  Latitude  Longitude    M    D     H
0         24.0      37.0  101792.0  50.10700      19.82  6.0  3.0  11.0
1         24.0      37.0  101792.0  50.10403      19.82  6.0  3.0  11.0
2         24.0      37.0  101792.0  50.10106      19.82  6.0  3.0  11.0

In [54]:
#przewidziało
prediction = model.predict(points)
prediction

array([7.63, 7.63, 7.64, ..., 9.66, 9.21, 9.21])

In [55]:
points["prediction_pm10"] = prediction
points[:3]

temperature  humidity  pressure  Latitude  ...    M    D     H  prediction_pm10
0         24.0      37.0  101792.0  50.10700  ...  6.0  3.0  11.0             7.63
1         24.0      37.0  101792.0  50.10403  ...  6.0  3.0  11.0             7.63
2         24.0      37.0  101792.0  50.10106  ...  6.0  3.0  11.0             7.64

[3 rows x 9 columns]

In [60]:
points.describe()

temperature  humidity  pressure  ...       D       H  prediction_pm10
count       1575.0    1575.0    1575.0  ...  1575.0  1575.0      1575.000000
mean          24.0      37.0  101792.0  ...     3.0    11.0         7.899054
std            0.0       0.0       0.0  ...     0.0     0.0         0.769865
min           24.0      37.0  101792.0  ...     3.0    11.0         6.330000
25%           24.0      37.0  101792.0  ...     3.0    11.0         7.385000
50%           24.0      37.0  101792.0  ...     3.0    11.0         7.830000
75%           24.0      37.0  101792.0  ...     3.0    11.0         8.465000
max           24.0      37.0  101792.0  ...     3.0    11.0        10.030000

[8 rows x 9 columns]

In [57]:
!pip -q install folium
import folium

In [58]:
location = [50.0614 ,19.9366]

m = folium.Map(location=location, zoom_start=17)


for ind in points.index: 
    tooltip_txt = 'PM10:' + str(points['prediction_pm10'][ind])
    folium.Circle(
          location=[float(points['Latitude'][ind]), float(points['Longitude'][ind])], 
          radius=165,
          # popup="Laurelhurst Park",
          color="#3186cc",
          # fill=True,
          fill_color="#3186cc",
          tooltip= tooltip_txt
      ).add_to(m)
m

In [61]:
name_file = "index.html"

m.save(name_file)
from google.colab import files
files.download(name_file) 

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

10.3 Utworzenie modelu K-najbliższych sąsiadów -regression (odległość, haversine distance- odległość km )